name: Build LaTeX document

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
    steps:
      - name: Set up Git repository and make resume
        uses: actions/checkout@v1

      - name: Build resume
        run: make
